const $=id=>document.getElementById(id);
const options={sangsang:{example:158800,extra:90000,bbq:35000,policy:'상상초당: 5인 숯·그릴 35,000원은 안내 규정에 따른 계산값입니다. 실제 적용금액과 날씨에 따른 운영을 확인하세요.'},santa:{example:129000,extra:20000,bbq:20000,policy:'산타비치: 101호 기준입니다. 5번째 인원의 매트·침구와 10월 말 테라스 운영 여부를 확인하세요.'},gangmun:{example:172100,extra:90000,bbq:20000,policy:'더강문: 40대 중반 남성 5명 예약 허용 여부를 먼저 확인하세요. 미온수·인원요금이 상품에 포함됐는지도 확인하세요.'}};
let exampleMode=false;
const won=n=>Math.round(n).toLocaleString('ko-KR')+'원';
function calculate(){const key=$('stay').value,d=options[key];$('pool-row').hidden=key!=='gangmun';$('policy').textContent=d.policy;const r=$('room').value;const food=Number($('food').value);if(r===''||!$('room').checkValidity()||!$('food').checkValidity()){$('total').textContent='—';$('per').textContent='—';$('breakdown').textContent='객실료와 식비를 0 이상의 유효한 금액으로 입력해 주세요.';return;}const room=Number(r),extra=$('included').checked?0:d.extra,bbq=$('bbq').checked?d.bbq:0,pool=key==='gangmun'&&$('pool').checked?80000:0,total=room+extra+bbq+pool+food*5;$('total').textContent=won(total);$('per').textContent=won(total/5);$('breakdown').textContent=`객실 ${won(room)} + 추가인원 ${won(extra)} + 그릴 ${won(bbq)} + 미온수 ${won(pool)} + 식비 5인 ${won(food*5)}. 1인 금액은 원 단위 반올림.`;}
$('stay').addEventListener('change',()=>{exampleMode=false;$('room').value='';$('included').checked=false;$('mode').textContent='객실료 미입력 · 선택한 숙소의 견적을 입력해 주세요.';calculate();});
['room','food','included','bbq','pool'].forEach(id=>$(id).addEventListener('input',()=>{if(id==='room'){exampleMode=false;$('mode').textContent='직접 입력한 객실료 기준 · 실시간 예약 요금과 자동 연동되지 않습니다.';}calculate();}));
$('example').addEventListener('click',()=>{exampleMode=true;$('room').value=options[$('stay').value].example;$('included').checked=false;$('mode').textContent='참고 예시 모드 · 다른 날짜/날짜 미표시 요금으로 계산합니다. 10월 31일 확정가가 아닙니다.';calculate();});
$('calculator').addEventListener('submit',e=>e.preventDefault());
async function copy(text){try{await navigator.clipboard.writeText(text);$('toast').textContent='복사했습니다.';$('toast').style.display='block';setTimeout(()=>$('toast').style.display='none',2400);}catch{window.prompt('아래 내용을 복사해 주세요.',text);}}
$('share').addEventListener('click',()=>copy(location.href.split('#')[0]));$('copy-inquiry').addEventListener('click',()=>copy($('inquiry').textContent));$('print').addEventListener('click',()=>window.print());calculate();
